-keep class org.lsposed.** { *; }
-keep class com.android.tools.** { *; }
-keep class com.google.gson.** { *; }
-keep class com.beust.jcommander.** { *; }
-keep class com.wind.meditor.** { *; }
-keep class org.bouncycastle.** { *; }
-keep class com.google.common.** { *; }
-keep class org.apache.commons.io.** { *; }
